[package]
name = "cargo-scaffold"
version = "0.1.0"
authors = ["Benjamin Coenen <5719034+bnjjj@users.noreply.github.com>"]
edition = "2018"
description = "cargo scaffold lets you scaffold and generate an entire stack based on a simple toml file and make templating into your templates"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/iomentum/cargo-scaffold"
keywords = ["scaffold", "generate", "cargo", "templating"]

[dependencies]
cargo = "0.46.1"
anyhow = "1.0.32"
clap = "2.33.3" 
serde = { version = "1.0.115", features = ["derive"] }
dialoguer = "0.6.2"
handlebars = "3.4.0"
walkdir = "2.3.1"
toml = "0.5.6"
heck = "0.3.1"
git2 = "0.13.9"
md5 = "0.7.0"

[[bin]]
path = "src/main.rs"
name = "cargo-scaffold"
